### ISSUE TITLE
We should not give points to all when a game ends with draw

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#418] opened 2020-09-15 21:53 UTC
Regarding #401 we should remove the option to give points when there is a draw

**Comment by salvob41** [comment] 2020-09-15 21:55
maybe @ekorina knows more?

**Comment by ekorina** [comment] 2020-09-16 08:18
Duplicate of #410. Please check if the problem is already known before adding a new issue.

**Closed by ekorina** 2020-09-16 08:18 UTC
Labels: game_design, ui
